### ISSUE TITLE
Encounter Mechanic

### ISSUE THREAD

**Issue by tmoss343** [AlexanderSmith/Soteria#17]
<h1>Description</h1>

<h2>Design Perspective</h2>

This is  how the base encounter with the shadow creatures. it is laid out step 

![encounter1](https://cloud.githubusercontent.com/assets/6886741/6434835/4aba684a-c056-11e4-8046-d80e7711df67.jpg)
Above is just the player on screen

![encounter2](https://cloud.githubusercontent.com/assets/6886741/6434838/5a425ee4-c056-11e4-8d48-878f9e82e6cf.jpg)
The player advances through the level

![encounter3](https://cloud.githubusercontent.com/assets/6886741/6434876/f87473f4-c056-11e4-80e3-9cc15d592934.jpg)
The enemies spawn ideally out of the view of the player

![encounter4](https://cloud.githubusercontent.com/assets/6886741/6434884/17499d0e-c057-11e4-90a2-870679950d60.jpg)
Ideally the enemies will have a super rough patrol AI and make their way towards the player eventually

![encounter5](https://cloud.githubusercontent.com/assets/6886741/6434891/30bac8d0-c057-11e4-8c16-c880c0170748.jpg)
The creatures should have a field of view, this does not need to be shown to the player. If the player is in this field of view then the creatures will pursue. If the player exits this field of view then they will stop 

![encounter6](https://cloud.githubusercontent.com/assets/6886741/6434921/d92cc70c-c057-11e4-8531-9029ee775e56.jpg)
The creatures operate with basically two colliders that they use to detect the player. If the player falls within the range of the green collider then the creatures will pursue. If the player falls within the pink collider range then the creatures will instigate the "consuming"

![encounter7](https://cloud.githubusercontent.com/assets/6886741/6434969/32d2f0aa-c059-11e4-95bd-15c93770e77e.jpg)
The creatures should themselves remain close to the character but not actually move towards her. The effect of "consuming" the player will be done separately. At this point the player's view should be turned in the opposite direction of the enemies that have surrounded them. A "celestial beam of light" should appear in front of the player's view. Do not worry about how any of these assets look right now

Now here is where the player has two choices. By walking in the direction of the beam of light, the player will be transported to the center of the town square and remove one "token" from the player's inventory. The other choice is to turn around and face the creatures. If the player does this, they must press the space bar a certain number of times within a small window of time, say 5 seconds. If they fail to do this, they will spawn at the dock location and lose all of their inventory. 

<h2>Programming Perspective</h2>

To accomplish this mechanic the way the designers have outlined with the system that we already have in place should only take the addition of the consuming and overcoming the consuming and a tweak to the alert system currently in place in the basic enemy ai system.

Basically the initial idea will be to use the BasicAggroSystem class we have right now for the radius checks, the function might have to be modified to fit this new bill but it is is the same basic idea. Then when you get into the inner radius as described above you will kick off the consuming event where the player will be turned around and presented with the token option. If the player makes contact with the token by walking there with there character then it will transport them back to the center of town (at this point transporting back to the starting point or reloading the scene should suffice). If the player doesn't want to take the token and would rather confront the consuming then we are going to have to track if they are looking at the shadow creature or still facing towards the token (<a href="http://docs.unity3d.com/ScriptReference/Vector3.Dot.html">Dot product?</a>). When they are facing and they press space 5 times then they will overcome the shadow creature encounter and the creature can dissipate. It can spawn an object when it dies that can be picked up by the character when it walks over it (fear residue) for now this can just disappear when you walk over it (this will be part of the framework to hook in the player data later). Overall there will be a timer that will handle whether or not you will lose the encounter. If you do not take the token or overcome the shadow creatures quickly enough you will fail.  

//to do finalize whether the lose condition timer starts when the player turns around or when the token appears. 

<h1>Requirements</h1>

-Proper radial aggro system for field of view to chase the player and to begin the consuming encounter. 
-Token appears when consuming starts, if you collide with the token you are sent back to the beginning of the scene. 
-Tracking if the player is overcoming the consuming by making sure the player is facing the shadow creature and tracking the amount of times they hit space. 
-Timer failure system, can just restart the scene similar to the token for now. 
-Dissipation of a shadow creature when it is over come and the drop of fear residue that can be "picked up" or collided with and then removing the object from the scene. 

<h1>Previous Work</h1>

Issue #2 Actor Base

<h1>Notes</h1>

This story's writing is currently a work in progress and subject to change.

**Comment by FierceLlama** [comment]
Basic encounter method established.  Scene resets on Soteria statue click or if game timer runs out -- timer does not currently account for player trying to fight back against shadow creatures.
