### ISSUE TITLE
Actor Base

### ISSUE THREAD

**Issue by tmoss343** [AlexanderSmith/Soteria#2]
Description

Making the base class and then probably test player and enemy classes for an actor with basic movement.

Requirements

Make a class that has basic movement functions to maneuver 3D space for both a player and an enemy.

Previous work

None

Notes

None

**Comment by severn2** [comment]
@tmoss343 

If you could write more formally what the story's requirements / description / side notes or previous work are that would be great.

**Comment by severn2** [comment]
Status? 
@tmoss343

**Comment by FierceLlama** [comment]
Done
